name: Code Style

on: [ push, pull_request ]

jobs:
  test-php:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install composer dependencies
      run: composer install

    - name: Run composer tests
      run: composer test
